research_company_task:
  description: >
    Search database to look up this company's stock information: {company_name}.
    The goal is to prepare enough information to make an informed analysis of the company's stock performance
    (the information of HSI can be search by querying ^HSI in the database)
    Please do not use outdated information, the information on the database is for current.
  expected_output: >
    All of the relevant financial information about the specific company's stock performance with a header named Financial Research of {company_name}, please includes the risk, ROI, sharpe ratio, and the correlation to HSI.
    Output the result in markdown format. Remember to add | ----------- | ----------- | for the markdown tables and add new line before and after it.
    
    Here is an example output:
    **Financial Research of 0001.HK**

    | Category          | Value   |
    | ----------------- | ------- |
    | Risk              | 20.92   |
    | ROI               | -18.13  |
    | Sharpe Ratio      | -0.87   |
    | Correlation to HSI| 0.75    |
    | P/E Ratio         | 6.14    |
    | Variance          | 2.20    |

    The stock with id 0001.HK, CK Hutchison Holdings Limited, has a risk of 20.92, which is higher than the average risk level. The ROI (return on investment) is negative at -18.13%, indicating that the company is not generating profits for its investors. The Sharpe Ratio is also negative at -0.87, suggesting that the stock's performance is poor even when considering its low risk-free rate. The correlation to HSI (Hang Seng Index) is 0.75, meaning that the stock's price movements are moderately positively correlated with the overall market. The P/E Ratio is 6.14, which is below the average P/E ratio, indicating that the stock may be undervalued. The variance of the stock is 2.20, which measures the volatility of the stock's returns and shows that it has a moderate level of risk.
    Overall, the financial performance of CK Hutchison Holdings Limited is poor, with negative ROI and Sharpe Ratio. However, the stock may be undervalued, as indicated by its low P/E ratio, and could be a potential investment opportunity for those willing to take on higher risk. Investors should carefully consider their investment goals and risk tolerance before investing in this stock.

analyze_company_task:
  description: >
    Take {company_name}'s financial information from the researcher, analyze it, and provide a financial analysis, including: risk, ROI, sharpe ratio, P/E ratio, VaR, Valuation metrics.
  expected_output: >
    A nicely formatted analysis with a header named Financial Analysis of {company_name} including all of the financial metrics necessary for a thorough financial analysis of a company
    Output the result in markdown format. Remember to add | ----------- | ----------- | for the markdown tables and add new line before and after it.

    Here is an example output:
    **Financial Analysis of 0001.HK**

    * **Risk:** The risk level of CK Hutchison Holdings Limited is 20.92, which is higher than the average risk level. This indicates that there is a greater potential for financial loss when investing in this company compared to other investment opportunities.
    * **ROI (Return on Investment):** The ROI for CK Hutchison Holdings Limited is negative at -18.13%, indicating that the company is not generating profits for its investors. This is a significant red flag, as it suggests that the company may be struggling to maintain financial stability.
    * **Sharpe Ratio:** The Sharpe Ratio of CK Hutchison Holdings Limited is also negative at -0.87, suggesting that the stock's performance is poor even when considering its low risk-free rate. This further supports the idea that this company may not be a strong investment opportunity.
    * **Correlation to HSI:** The correlation to HSI (Hang Seng Index) for CK Hutchison Holdings Limited is 0.75, meaning that the stock's price movements are moderately positively correlated with the overall market. This indicates that the company's performance may be influenced by broader economic trends.
    * **P/E Ratio:** The P/E Ratio for CK Hutchison Holdings Limited is 6.14, which is below the average P/E ratio. This suggests that the stock may be undervalued and could potentially offer a good investment opportunity for those willing to take on higher risk.
    * **Variance:** The variance of CK Hutchison Holdings Limited's stock returns is 2.20, which measures the volatility of the stock's returns. This moderate level of risk indicates that there may be some fluctuations in the company's performance over time.
    Overall, the financial performance of CK Hutchison Holdings Limited is poor, with negative ROI and Sharpe Ratio. However, the stock may be undervalued, as indicated by its low P/E ratio, and could be a potential investment opportunity for those willing to take on higher risk. Investors should carefully consider their investment goals and risk tolerance before investing in this stock.
summarize_company_task:
  description: >
    Take the financial research and analysis that is previously provided and generate a precise and clear summary which includes all the previous information,
    Additional investment advice could also be given based on the given data
  expected_output: >
    A nicely formatted summary with a header named Financial Summary of {company_name} including companies's stock performances and all of the financial metrics necessary for a thorough financial analysis of a company 
    with the example template, give reasons for you recommendations such as BUY, SELL, and HOLD: 
    Here is an example output:
    **Financial Analysis of 0001.HK**

    We issue a BUY recommendation on BOC Hong Kong (Holdings) Limited based on a one-year target price of 26.2, 
    offering a 8.7% upside potential from its closing price of 24.6 on June 18 2024. Our recommendation is 
    primarily driven by:\

    Strong Financials: BOC Hong Kong (Holdings) Limited (2388.HK) has demonstrated robust financial performance, with a healthy ROI of 7.79% and a Sharpe Ratio of 0.35, indicating solid risk-adjusted returns. The company's P/E ratio of 7.93 suggests that the stock is currently undervalued compared to its peers.
    Moderate Risk Profile: The stock's risk level, as measured by its 22.08% volatility, is within an acceptable range for investors. Additionally, the company's 95% VaR of 2.33 implies a relatively conservative risk exposure.
    Positive Market Outlook: The stock's correlation of 0.73 with the Hang Seng Index (HSI) suggests that it is reasonably well-aligned with the broader market performance, providing investors with a degree of diversification.
    Upside Potential: Based on our analysis, we have set a one-year target price of HK$26.2 for BOC Hong Kong (Holdings) Limited, which represents an 8.7% upside potential from the stock's closing price of HK$24.6 on June 18, 2024.

    Recommendation: Given the company's favorable financial metrics, manageable risk profile, and the identified upside potential, we issue a BUY recommendation on BOC Hong Kong (Holdings) Limited (2388.HK).

    Output the result in markdown format. Remember to add | ----------- | ----------- | for the markdown tables and add new line before and after it.
    